import LocalStorage from "../services/LocalStorage/LocalStorage"

function setTestingData() {
    const data = [
        {
            Const: "tt0167261",
            "Original Country": null,
            "Poster Path": null,
            "TMDB id": null,
            "Your Rating": "10",
            "Date Rated": "2021-06-15",
            Title: "Володар перснів: Дві вежі",
            "Original Title": "The Lord of the Rings: The Two Towers",
            URL: "https://www.imdb.com/title/tt0167261",
            "Title Type": "Movie",
            "IMDb Rating": "8.8",
            "Runtime (mins)": "179",
            Year: "2002",
            Genres: "Drama, Adventure, Fantasy",
            "Num Votes": "1933122",
            "Release Date": "2003-01-23",
            Directors: "Peter Jackson",
        },
        {
            Const: "tt1375666",
            "Original Country": null,
            "Poster Path": null,
            "TMDB id": null,
            "Your Rating": "7",
            "Date Rated": "2021-06-15",
            Title: "Початок",
            "Original Title": "Inception",
            URL: "https://www.imdb.com/title/tt1375666",
            "Title Type": "Movie",
            "IMDb Rating": "8.8",
            "Runtime (mins)": "148",
            Year: "2010",
            Genres: "Sci-Fi, Thriller, Action, Adventure",
            "Num Votes": "2779273",
            "Release Date": "2010-07-22",
            Directors: "Christopher Nolan",
        },
        {
            Const: "tt0137523",
            "Original Country": null,
            "Poster Path": null,
            "TMDB id": null,
            "Your Rating": "9",
            "Date Rated": "2021-06-15",
            Title: "Бійцівський клуб",
            "Original Title": "Fight Club",
            URL: "https://www.imdb.com/title/tt0137523",
            "Title Type": "Movie",
            "IMDb Rating": "8.8",
            "Runtime (mins)": "139",
            Year: "1999",
            Genres: "Drama, Crime, Thriller",
            "Num Votes": "2565689",
            "Release Date": "1999-10-15",
            Directors: "David Fincher",
        },
        {
            Const: "tt0109830",
            "Original Country": null,
            "Poster Path": null,
            "TMDB id": null,
            "Your Rating": "9",
            "Date Rated": "2021-06-15",
            Title: "Форрест Ґамп",
            "Original Title": "Forrest Gump",
            URL: "https://www.imdb.com/title/tt0109830",
            "Title Type": "Movie",
            "IMDb Rating": "8.8",
            "Runtime (mins)": "142",
            Year: "1994",
            Genres: "Romance, Drama",
            "Num Votes": "2464418",
            "Release Date": "1994-07-06",
            Directors: "Robert Zemeckis",
        },
        {
            Const: "tt0120737",
            "Original Country": null,
            "Poster Path": null,
            "TMDB id": null,
            "Your Rating": "10",
            "Date Rated": "2021-06-15",
            Title: "Володар перснів: Хранителі персня",
            "Original Title":
                "The Lord of the Rings: The Fellowship of the Ring",
            URL: "https://www.imdb.com/title/tt0120737",
            "Title Type": "Movie",
            "IMDb Rating": "8.9",
            "Runtime (mins)": "178",
            Year: "2001",
            Genres: "Drama, Adventure, Fantasy",
            "Num Votes": "2178981",
            "Release Date": "2002-02-08",
            Directors: "Peter Jackson",
        },
        {
            Const: "tt0110912",
            "Original Country": null,
            "Poster Path": null,
            "TMDB id": null,
            "Your Rating": "9",
            "Date Rated": "2021-06-15",
            Title: "Кримінальне чтиво",
            "Original Title": "Pulp Fiction",
            URL: "https://www.imdb.com/title/tt0110912",
            "Title Type": "Movie",
            "IMDb Rating": "8.8",
            "Runtime (mins)": "154",
            Year: "1994",
            Genres: "Crime, Drama",
            "Num Votes": "2407225",
            "Release Date": "1994-10-14",
            Directors: "Quentin Tarantino",
        },
        {
            Const: "tt0167260",
            "Original Country": null,
            "Poster Path": null,
            "TMDB id": null,
            "Your Rating": "10",
            "Date Rated": "2021-06-15",
            Title: "Володар перснів: Повернення короля",
            "Original Title": "The Lord of the Rings: The Return of the King",
            URL: "https://www.imdb.com/title/tt0167260",
            "Title Type": "Movie",
            "IMDb Rating": "9.0",
            "Runtime (mins)": "201",
            Year: "2003",
            Genres: "Drama, Adventure, Fantasy",
            "Num Votes": "2139334",
            "Release Date": "2004-01-22",
            Directors: "Peter Jackson",
        },
        {
            Const: "tt0108052",
            "Original Country": null,
            "Poster Path": null,
            "TMDB id": null,
            "Your Rating": "10",
            "Date Rated": "2021-06-15",
            Title: "Список Шиндлера",
            "Original Title": "Schindler's List",
            URL: "https://www.imdb.com/title/tt0108052",
            "Title Type": "Movie",
            "IMDb Rating": "9.0",
            "Runtime (mins)": "195",
            Year: "1993",
            Genres: "Biography, History, Drama",
            "Num Votes": "1570265",
            "Release Date": "1994-02-04",
            Directors: "Steven Spielberg",
        },
        {
            Const: "tt0468569",
            "Original Country": null,
            "Poster Path": null,
            "TMDB id": null,
            "Your Rating": "8",
            "Date Rated": "2021-06-15",
            Title: "Темний лицар",
            "Original Title": "The Dark Knight",
            URL: "https://www.imdb.com/title/tt0468569",
            "Title Type": "Movie",
            "IMDb Rating": "9.1",
            "Runtime (mins)": "152",
            Year: "2008",
            Genres: "Drama, Crime, Thriller, Action",
            "Num Votes": "3125206",
            "Release Date": "2008-08-14",
            Directors: "Christopher Nolan",
        },
        {
            Const: "tt5433138",
            "Original Country": null,
            "Poster Path": null,
            "TMDB id": null,
            "Your Rating": "5",
            "Date Rated": "2021-06-15",
            Title: "Форсаж 9: Нестримна сага",
            "Original Title": "F9",
            URL: "https://www.imdb.com/title/tt5433138",
            "Title Type": "Movie",
            "IMDb Rating": "5.2",
            "Runtime (mins)": "143",
            Year: "2021",
            Genres: "Action, Crime, Thriller",
            "Num Votes": "177665",
            "Release Date": "2021-06-17",
            Directors: "Justin Lin",
        },
        {
            Const: "tt0111161",
            "Original Country": null,
            "Poster Path": null,
            "TMDB id": null,
            "Your Rating": "10",
            "Date Rated": "2021-06-15",
            Title: "Втеча з Шоушенка",
            "Original Title": "The Shawshank Redemption",
            URL: "https://www.imdb.com/title/tt0111161",
            "Title Type": "Movie",
            "IMDb Rating": "9.3",
            "Runtime (mins)": "142",
            Year: "1994",
            Genres: "Drama",
            "Num Votes": "3149774",
            "Release Date": "1994-10-14",
            Directors: "Frank Darabont",
        },
    ]
    const updatedData = [
        {
            Const: "tt0167261",
            "Original Country": ["US"],
            "Poster Path": "/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg",
            "TMDB id": 121,
            "Your Rating": "10",
            "Date Rated": "2021-06-15",
            Title: "Володар перснів: Дві вежі",
            "Original Title": "The Lord of the Rings: The Two Towers",
            URL: "https://www.imdb.com/title/tt0167261",
            "Title Type": "Movie",
            "IMDb Rating": "8.8",
            "Runtime (mins)": "179",
            Year: "2002",
            Genres: "Drama, Adventure, Fantasy",
            "Num Votes": "1933122",
            "Release Date": "2003-01-23",
            Directors: "Peter Jackson",
        },
        {
            Const: "tt1375666",
            "Original Country": ["US", "GB"],
            "Poster Path": "/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg",
            "TMDB id": 27205,
            "Your Rating": "7",
            "Date Rated": "2021-06-15",
            Title: "Початок",
            "Original Title": "Inception",
            URL: "https://www.imdb.com/title/tt1375666",
            "Title Type": "Movie",
            "IMDb Rating": "8.8",
            "Runtime (mins)": "148",
            Year: "2010",
            Genres: "Sci-Fi, Thriller, Action, Adventure",
            "Num Votes": "2779273",
            "Release Date": "2010-07-22",
            Directors: "Christopher Nolan",
        },
        {
            Const: "tt0137523",
            "Original Country": ["US"],
            "Poster Path": "/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
            "TMDB id": 550,
            "Your Rating": "9",
            "Date Rated": "2021-06-15",
            Title: "Бійцівський клуб",
            "Original Title": "Fight Club",
            URL: "https://www.imdb.com/title/tt0137523",
            "Title Type": "Movie",
            "IMDb Rating": "8.8",
            "Runtime (mins)": "139",
            Year: "1999",
            Genres: "Drama, Crime, Thriller",
            "Num Votes": "2565689",
            "Release Date": "1999-10-15",
            Directors: "David Fincher",
        },
        {
            Const: "tt0109830",
            "Original Country": ["US"],
            "Poster Path": "/saHP97rTPS5eLmrLQEcANmKrsFl.jpg",
            "TMDB id": 13,
            "Your Rating": "9",
            "Date Rated": "2021-06-15",
            Title: "Форрест Ґамп",
            "Original Title": "Forrest Gump",
            URL: "https://www.imdb.com/title/tt0109830",
            "Title Type": "Movie",
            "IMDb Rating": "8.8",
            "Runtime (mins)": "142",
            Year: "1994",
            Genres: "Romance, Drama",
            "Num Votes": "2464418",
            "Release Date": "1994-07-06",
            Directors: "Robert Zemeckis",
        },
        {
            Const: "tt0120737",
            "Original Country": ["US"],
            "Poster Path": "/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
            "TMDB id": 120,
            "Your Rating": "10",
            "Date Rated": "2021-06-15",
            Title: "Володар перснів: Хранителі персня",
            "Original Title":
                "The Lord of the Rings: The Fellowship of the Ring",
            URL: "https://www.imdb.com/title/tt0120737",
            "Title Type": "Movie",
            "IMDb Rating": "8.9",
            "Runtime (mins)": "178",
            Year: "2001",
            Genres: "Drama, Adventure, Fantasy",
            "Num Votes": "2178981",
            "Release Date": "2002-02-08",
            Directors: "Peter Jackson",
        },
        {
            Const: "tt0110912",
            "Original Country": ["US"],
            "Poster Path": "/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg",
            "TMDB id": 680,
            "Your Rating": "9",
            "Date Rated": "2021-06-15",
            Title: "Кримінальне чтиво",
            "Original Title": "Pulp Fiction",
            URL: "https://www.imdb.com/title/tt0110912",
            "Title Type": "Movie",
            "IMDb Rating": "8.8",
            "Runtime (mins)": "154",
            Year: "1994",
            Genres: "Crime, Drama",
            "Num Votes": "2407225",
            "Release Date": "1994-10-14",
            Directors: "Quentin Tarantino",
        },
        {
            Const: "tt0167260",
            "Original Country": ["US"],
            "Poster Path": "/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
            "TMDB id": 122,
            "Your Rating": "10",
            "Date Rated": "2021-06-15",
            Title: "Володар перснів: Повернення короля",
            "Original Title": "The Lord of the Rings: The Return of the King",
            URL: "https://www.imdb.com/title/tt0167260",
            "Title Type": "Movie",
            "IMDb Rating": "9.0",
            "Runtime (mins)": "201",
            Year: "2003",
            Genres: "Drama, Adventure, Fantasy",
            "Num Votes": "2139334",
            "Release Date": "2004-01-22",
            Directors: "Peter Jackson",
        },
        {
            Const: "tt0108052",
            "Original Country": ["US"],
            "Poster Path": "/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
            "TMDB id": 424,
            "Your Rating": "10",
            "Date Rated": "2021-06-15",
            Title: "Список Шиндлера",
            "Original Title": "Schindler's List",
            URL: "https://www.imdb.com/title/tt0108052",
            "Title Type": "Movie",
            "IMDb Rating": "9.0",
            "Runtime (mins)": "195",
            Year: "1993",
            Genres: "Biography, History, Drama",
            "Num Votes": "1570265",
            "Release Date": "1994-02-04",
            Directors: "Steven Spielberg",
        },
        {
            Const: "tt0468569",
            "Original Country": ["US"],
            "Poster Path": "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
            "TMDB id": 155,
            "Your Rating": "8",
            "Date Rated": "2021-06-15",
            Title: "Темний лицар",
            "Original Title": "The Dark Knight",
            URL: "https://www.imdb.com/title/tt0468569",
            "Title Type": "Movie",
            "IMDb Rating": "9.1",
            "Runtime (mins)": "152",
            Year: "2008",
            Genres: "Drama, Crime, Thriller, Action",
            "Num Votes": "3125206",
            "Release Date": "2008-08-14",
            Directors: "Christopher Nolan",
        },
        {
            Const: "tt5433138",
            "Original Country": ["US"],
            "Poster Path": "/deEmLILTPejEb6OGsXRJ5MCvyDW.jpg",
            "TMDB id": 385128,
            "Your Rating": "5",
            "Date Rated": "2021-06-15",
            Title: "Форсаж 9: Нестримна сага",
            "Original Title": "F9",
            URL: "https://www.imdb.com/title/tt5433138",
            "Title Type": "Movie",
            "IMDb Rating": "5.2",
            "Runtime (mins)": "143",
            Year: "2021",
            Genres: "Action, Crime, Thriller",
            "Num Votes": "177665",
            "Release Date": "2021-06-17",
            Directors: "Justin Lin",
        },
        {
            Const: "tt0111161",
            "Original Country": ["US"],
            "Poster Path": "/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg",
            "TMDB id": 278,
            "Your Rating": "10",
            "Date Rated": "2021-06-15",
            Title: "Втеча з Шоушенка",
            "Original Title": "The Shawshank Redemption",
            URL: "https://www.imdb.com/title/tt0111161",
            "Title Type": "Movie",
            "IMDb Rating": "9.3",
            "Runtime (mins)": "142",
            Year: "1994",
            Genres: "Drama",
            "Num Votes": "3149774",
            "Release Date": "1994-10-14",
            Directors: "Frank Darabont",
        },
    ]
    
    LocalStorage.set("moviesDB", data)
    LocalStorage.set("updatedMoviesDB", updatedData)
}

export default setTestingData